const BINANCE_FUTURES_LIST = ['GLMRUSDT', '1000SHIBUSDT','CRVUSDT','DYDXUSDT','DOGEUSDT','CVXUSDT','ANTUSDT','SFPUSDT','HIGHUSDT','NKNUSDT','LINKUSDT',
                  'COTIUSDT','FTMUSDT','ENSUSDT','TRXUSDT','KNCUSDT','1000FLOKIUSDT','MTLUSDT','PEOPLEUSDT','BALUSDT','TOMOUSDT',
                  'AAVEUSDT','MASKUSDT','AUDIOUSDT','CTKUSDT','XMRUSDT','LDOUSDT','SNXUSDT','LQTYUSDT','LRCUSDT','ROSEUSDT',
                  'KLAYUSDT','LTCUSDT','GTCUSDT','GALAUSDT','NEARUSDT','AXSUSDT','ARUSDT','CHRUSDT','ETHUSDT','STORJUSDT',
                  'XLMUSDT','ALPHAUSDT','ANKRUSDT','SPELLUSDT','BNBUSDT','GALUSDT','IOTXUSDT','DENTUSDT','EOSUSDT','BTCDOMUSDT',
                  'YFIUSDT','MATICUSDT','RADUSDT','IMXUSDT','VETUSDT','IDUSDT','OMGUSDT','ICPUSDT','BTCUSDT','1000LUNCUSDT',
                  'LUNA2USDT','DEFIUSDT','LPTUSDT','XTZUSDT','WAVESUSDT','ALGOUSDT','IOTAUSDT','EGLDUSDT','SANDUSDT','SOLUSDT',
                  'ACHUSDT','HOTUSDT','MINAUSDT','RENUSDT','DARUSDT','INJUSDT','DUSKUSDT','ONEUSDT','BNXUSDT','ETCUSDT',
                  'NEOUSDT','AVAXUSDT','BANDUSDT','GRTUSDT','MANAUSDT','STGUSDT','UMAUSDT','ATOMUSDT','ICXUSDT','COMPUSDT',
                  'ADAUSDT','ONTUSDT','DOTUSDT','RLCUSDT','APEUSDT','JASMYUSDT','OCEANUSDT','RUNEUSDT','ZECUSDT','GMTUSDT',
                  'SSVUSDT','DASHUSDT','REEFUSDT','CTSIUSDT','CELRUSDT','FILUSDT','BELUSDT','IOSTUSDT','ENJUSDT','SKLUSDT',
                  '1000PEPEUSDT','RVNUSDT','ZILUSDT','DGBUSDT','1INCHUSDT','ALICEUSDT','ARBUSDT','THETAUSDT','CELOUSDT','ZENUSDT',
                  'SXPUSDT','OGNUSDT','ARPAUSDT','FLOWUSDT','1000XECUSDT','UNIUSDT','XRPUSDT','LITUSDT','PHBUSDT','TRBUSDT',
                  'OPUSDT','AGIXUSDT','BCHUSDT','QTUMUSDT','XEMUSDT','KEYUSDT','CHZUSDT','STXUSDT','BLZUSDT','MDTUSDT',
                  'FOOTBALLUSDT','UNFIUSDT','KAVAUSDT','RSRUSDT','ZRXUSDT','SUSHIUSDT','FLMUSDT','C98USDT','HBARUSDT','ATAUSDT',
                  'BATUSDT','FETUSDT','MKRUSDT','CFXUSDT','COMBOUSDT','ASTRUSDT','API3USDT','WOOUSDT','KSMUSDT','RNDRUSDT',
                  'XVGUSDT','BAKEUSDT','STMXUSDT','GMXUSDT', 'STRAXUSDT', 'BICOUSDT', 'GLMRUSDT', 'FRONTUSDT', 'ARKUSDT', 'HIFIUSDT', 
                  'CYBERUSDT', 'SEIUSDT', 'OXTUSDT', 'BNTUSDT', 'DODOUSDT', 'YGGUSDT', 'AGLDUSDT', 'ARKMUSDT', 'PENDLEUSDT', 'WLDUSDT',
                   'MAVUSDT', 'NMRUSDT', 'SUIUSDT', 'IDEXUSDT', 'EDUUSDT', 'BLURUSDT', 'XVSUSDT', 'HFTUSDT', 'RDNTUSDT', 'JOEUSDT', 
                   'USDCUSDT', 'TRUUSDT', 'PERPUSDT', 'COCOSUSDT', 'AMBUSDT', 'LEVERUSDT', 'TLMUSDT', 'CKBUSDT', 'APTUSDT', 'USTCUSDT']

// const BINANCE_SPOT_LIST = ['BTCUSDT', 'ACAUSDT', '1INCHUSDT', 'AAVEUSDT', 'ACMUSDT', 'ADAUSDT', 'AKROUSDT', 'ALGOUSDT', 'ALICEUSDT', 'ALPACAUSDT', 'ALPHAUSDT', 
//                     'ANKRUSDT', 'ANTUSDT', 'ARDRUSDT', 'ARPAUSDT', 'ARUSDT', 'ASRUSDT', 'ATAUSDT', 'ATMUSDT', 'ATOMUSDT', 'AUDIOUSDT', 'AVAUSDT', 
//                     'AVAXUSDT', 'AXSUSDT', 'BADGERUSDT', 'BAKEUSDT', 'BALUSDT', 'BANDUSDT', 'BATUSDT', 'BCHUSDT', 'BELUSDT', 'BLZUSDT', 'BNBDOWNUSDT', 
//                     'BNBUPUSDT', 'BNTUSDT', 'BONDUSDT', 'BTCDOWNUSDT', 'BTCUPUSDT', 'BURGERUSDT', 'BUSDUSDT', 'C98USDT', 'CAKEUSDT', 'CELOUSDT', 
//                     'CELRUSDT', 'CFXUSDT', 'CHRUSDT', 'CHZUSDT', 'CKBUSDT', 'CLVUSDT', 'COMPUSDT', 'COSUSDT', 'COTIUSDT', 'CRVUSDT', 'CTKUSDT', 
//                     'CTSIUSDT', 'CTXCUSDT', 'CVCUSDT', 'DASHUSDT', 'DATAUSDT', 'DCRUSDT', 'DEGOUSDT', 'DENTUSDT', 'DEXEUSDT', 'DGBUSDT', 'DIAUSDT',
//                     'DOCKUSDT', 'DODOUSDT', 'DOGEUSDT', 'DOTUSDT', 'DREPUSDT', 'DUSKUSDT', 'EGLDUSDT', 'ENJUSDT', 'EOSUSDT', 'ERNUSDT', 'ETCUSDT',
//                     'ETHDOWNUSDT', 'ETHUPUSDT', 'EURUSDT', 'FARMUSDT', 'FETUSDT', 'FILUSDT', 'FIOUSDT', 'FIROUSDT', 'FISUSDT', 'FLMUSDT', 'FLOWUSDT', 
//                     'FORTHUSDT', 'FTMUSDT', 'FTTUSDT', 'FUNUSDT', 'GBPUSDT', 'GRTUSDT', 'GTCUSDT', 'HARDUSDT', 'HBARUSDT', 'HIVEUSDT', 'HOTUSDT', 
//                     'ICPUSDT', 'ICXUSDT', 'INJUSDT', 'IOSTUSDT', 'IOTAUSDT', 'IOTXUSDT', 'IRISUSDT', 'JSTUSDT', 'JUVUSDT', 'KAVAUSDT', 'KEYUSDT', 
//                     'KLAYUSDT', 'KMDUSDT', 'KNCUSDT', 'KSMUSDT', 'LINAUSDT', 'LINKUSDT', 'LITUSDT', 'LPTUSDT', 'LRCUSDT', 'LSKUSDT', 'LTCUSDT', 
//                     'LTOUSDT', 'LUNAUSDT', 'MANAUSDT', 'MASKUSDT', 'MATICUSDT', 'MBLUSDT', 'MDTUSDT', 'MDXUSDT', 'MINAUSDT', 'MKRUSDT', 'MLNUSDT', 
//                     'MTLUSDT', 'NEARUSDT', 'NEOUSDT', 'NMRUSDT', 'NULSUSDT', 'OCEANUSDT', 'OGNUSDT', 'OGUSDT', 'OMGUSDT', 'OMUSDT', 'ONEUSDT', 
//                     'ONGUSDT', 'ONTUSDT', 'ORNUSDT', 'OXTUSDT', 'PAXGUSDT', 'PERPUSDT', 'PHAUSDT', 'PNTUSDT', 'POLSUSDT', 'PONDUSDT', 'PSGUSDT', 
//                     'PUNDIXUSDT', 'QNTUSDT', 'QTUMUSDT', 'QUICKUSDT', 'RAYUSDT', 'REEFUSDT', 'RIFUSDT', 'RLCUSDT', 'ROSEUSDT', 'RSRUSDT', 'RUNEUSDT',
//                     'RVNUSDT', 'SANDUSDT', 'SCUSDT', 'SFPUSDT', 'SHIBUSDT', 'SKLUSDT', 'SLPUSDT', 'SNXUSDT', 'SOLUSDT', 'STMXUSDT', 'STORJUSDT',
//                     'STPTUSDT', 'STRAXUSDT', 'STXUSDT', 'SUNUSDT', 'SUPERUSDT', 'SUSHIUSDT', 'SXPUSDT', 'TFUELUSDT', 'THETAUSDT', 'TKOUSDT', 
//                     'TLMUSDT', 'TRBUSDT', 'TROYUSDT', 'TRUUSDT', 'TRXUSDT', 'TUSDUSDT', 'TWTUSDT', 'UMAUSDT', 'UNFIUSDT', 'UNIUSDT', 
//                     'UTKUSDT', 'VETUSDT', 'VITEUSDT', 'VTHOUSDT', 'WANUSDT', 'WAVESUSDT', 'WINGUSDT', 'WINUSDT', 'WNXMUSDT', 'WRXUSDT', 'XEMUSDT',
//                     'XLMUSDT', 'XMRUSDT', 'XRPUSDT', 'XTZUSDT', 'XVGUSDT', 'XVSUSDT', 'YFIUSDT', 'ZECUSDT', 'ZENUSDT', 'ZILUSDT', 'ZRXUSDT', 
//                     'BNBUSDT', 'ETHUSDT', 'RENUSDT', 'NKNUSDT', 'BARUSDT', 'MBOXUSDT', 'FORUSDT', 'REQUSDT', 'GHSTUSDT', 'WAXPUSDT', 'GNOUSDT', 
//                     'XECUSDT', 'ELFUSDT', 'DYDXUSDT', 'IDEXUSDT', 'VIDTUSDT', 'USDPUSDT', 'GALAUSDT', 'ILVUSDT', 'YGGUSDT', 'SYSUSDT', 'DFUSDT',
//                     'FIDAUSDT', 'FRONTUSDT', 'CVPUSDT', 'AGLDUSDT', 'RADUSDT', 'BETAUSDT', 'RAREUSDT', 'LAZIOUSDT', 'CHESSUSDT', 'ADXUSDT', 
//                     'AUCTIONUSDT', 'DARUSDT', 'BNXUSDT', 'MOVRUSDT', 'CITYUSDT', 'ENSUSDT', 'KP3RUSDT', 'QIUSDT', 'PORTOUSDT', 'POWRUSDT', 
//                     'VGXUSDT', 'JASMYUSDT', 'AMPUSDT', 'PLAUSDT', 'PYRUSDT', 'RNDRUSDT', 'ALCXUSDT', 'SANTOSUSDT', 'BICOUSDT', 'FLUXUSDT', 
//                     'FXSUSDT', 'VOXELUSDT', 'HIGHUSDT', 'CVXUSDT', 'PEOPLEUSDT', 'OOKIUSDT', 'SPELLUSDT', 'JOEUSDT', 'ACHUSDT', 'IMXUSDT', 
//                     'GLMRUSDT', 'LOKAUSDT', 'SCRTUSDT', 'API3USDT', 'BTTCUSDT', 'XNOUSDT', 'WOOUSDT', 'ALPINEUSDT', 'TUSDT', 
//                     'ASTRUSDT', 'GMTUSDT', 'KDAUSDT', 'APEUSDT', 'BSWUSDT', 'BIFIUSDT', 'MULTIUSDT', 'STEEMUSDT', 'MOBUSDT', 'NEXOUSDT', 
//                     'REIUSDT', 'GALUSDT', 'LDOUSDT', 'EPXUSDT', 'OPUSDT', 'LEVERUSDT', 'STGUSDT', 'LUNCUSDT', 'GMXUSDT', 'POLYXUSDT', 'APTUSDT', 
//                     'OSMOUSDT', 'HFTUSDT', 'PHBUSDT', 'HOOKUSDT', 'MAGICUSDT', 'HIFIUSDT', 'RPLUSDT', 'PROSUSDT', 'AGIXUSDT', 'GNSUSDT', 'SYNUSDT',
//                     'VIBUSDT', 'SSVUSDT', 'LQTYUSDT', 'AMBUSDT', 'USTCUSDT', 'GASUSDT', 'GLMUSDT', 'PROMUSDT', 'QKCUSDT', 'UFTUSDT', 'IDUSDT', 
//                     'ARBUSDT', 'LOOMUSDT', 'OAXUSDT', 'RDNTUSDT', 'WBTCUSDT', 'EDUUSDT', 'SUIUSDT', 'AERGOUSDT', 'PEPEUSDT', 'FLOKIUSDT', 
//                     'ASTUSDT', 'SNTUSDT', 'COMBOUSDT', 'MAVUSDT', 'PENDLEUSDT', 'ARKMUSDT', 'WBETHUSDT', 'WLDUSDT', 'FDUSDUSDT', 'SEIUSDT', 
//                     'CYBERUSDT', 'ARKUSDT', 'CREAMUSDT', 'GFTUSDT', 'IQUSDT', 'NTRNUSDT', 'TIAUSDT', 'MEMEUSDT', 'ORDIUSDT', 'BEAMXUSDT', 
//                     'PIVXUSDT', 'VICUSDT', 'BLURUSDT', 'VANRYUSDT', 'AEURUSDT', 'JTOUSDT', '1000SATSUSDT', 'MOVRUSDT']

const BINANCE_SPOT_LIST = ['ICXUSDT', 'CVPUSDT', 'ICXUSDT', 'SUIUSDT', 'CHZUSDT', 'CYBERUSDT',]
const BYBIT_SPOT_LIST = ['CYBERUSDT', 'CREAMUSDT', 'TONUSDT', 'BNBUSDT', 'ENAUSDT', 'AAVEUSDT', 'ENJUSDT', 'MASKUSDT', 'BATUSDT', 'BLURUSDT', 'LEVERUSDT', ]
const OKX_SPOT_LIST = ['TON-USDT', 'UTK-USDT', 'BNB-USDT', 'OM-USDT',]

// const OKX_SPOT_LIST = ["BTC-USDT", "ETH-USDT", "OKB-USDT", "MATIC-USDT", "XRP-USDT", "SOL-USDT", "DOGE-USDT", "OKT-USDT", "ORDI-USDT", 
//                        "AIDOGE-USDT", "1INCH-USDT", "AAVE-USDT", "ACA-USDT", "ACH-USDT", "ADA-USDT", "AERGO-USDT", "AGIX-USDT", "AGLD-USDT",
//                        "AKITA-USDT", "ALCX-USDT", "ALGO-USDT", "ALPHA-USDT", "ANT-USDT", "APE-USDT", "API3-USDT", "APM-USDT", "APT-USDT", 
//                        "AR-USDT", "ARB-USDT", "ARG-USDT", "AST-USDT", "ASTR-USDT", "ATOM-USDT", "AUCTION-USDT", "AVAX-USDT", "AXS-USDT", 
//                        "AZY-USDT", "BABYDOGE-USDT", "BADGER-USDT", "BAL-USDT", "BAND-USDT", "BAT-USDT", "BCH-USDT", "BETH-USDT", "BICO-USDT", 
//                        "BIGTIME-USDT", "BLOK-USDT", "BLUR-USDT", "BNB-USDT", "BNT-USDT", "BONE-USDT", "BORING-USDT", "BORA-USDT", "BRWL-USDT",
//                        "BSV-USDT", "BTT-USDT", "BZZ-USDT", "CAPO-USDT", "CEEK-USDT", "CELO-USDT", "CEL-USDT", "CELR-USDT", "CETUS-USDT", 
//                        "CFG-USDT", "CFX-USDT", "CGL-USDT", "CHZ-USDT", "CITY-USDT", "CLV-USDT", "COMP-USDT", "CONV-USDT", "CORE-USDT", 
//                        "CQT-USDT", "CRO-USDT", "CRV-USDT", "CSPR-USDT", "CTC-USDT", "CTXC-USDT", "CVC-USDT", "CVP-USDT", "CVX-USDT", "DAI-USDT",
//                        "DAO-USDT", "DASH-USDT", "DCR-USDT", "DEP-USDT", "DGB-USDT", "DIA-USDT", "DOME-USDT", "DORA-USDT", "DOSE-USDT", "DOT-USDT",
//                        "DYDX-USDT", "EGLD-USDT", "ELF-USDT", "ELON-USDT", "EM-USDT", "ENJ-USDT", "ENS-USDT", "EOS-USDT", "ERN-USDT", "ETC-USDT",
//                        "ETHW-USDT", "EURT-USDT", "FAME-USDT", "FET-USDT", "FIL-USDT", "FITFI-USDT", "FLM-USDT", "FLOW-USDT", "FLOKI-USDT", 
//                        "FLR-USDT", "FORTH-USDT", "FRONT-USDT", "FSN-USDT", "FTM-USDT", "FXS-USDT", "GALA-USDT", "GALFT-USDT", "GAL-USDT", 
//                        "GARI-USDT", "GAS-USDT", "GEAR-USDT", "GF-USDT", "GFT-USDT", "GHST-USDT", "GLM-USDT", "GLMR-USDT", "GMT-USDT", 
//                        "GMX-USDT", "GOAL-USDT", "GODS-USDT", "GOG-USDT", "GRT-USDT", "HBAR-USDT", "HC-USDT", "ICP-USDT", "ICX-USDT", 
//                        "ID-USDT", "IGU-USDT", "ILV-USDT", "IMX-USDT", "INJ-USDT", "IOST-USDT", "IOTA-USDT", "IQ-USDT", "JOE-USDT", 
//                        "JPG-USDT", "JST-USDT", "KAN-USDT", "KAR-USDT", "KCAL-USDT", "KDA-USDT", "KINE-USDT", "KISHU-USDT", "KLAY-USDT", 
//                        "KNC-USDT", "KONO-USDT", "KP3R-USDT", "KSM-USDT", "LAMB-USDT", "LAT-USDT", "LBR-USDT", "LDO-USDT", "LEASH-USDT", 
                     //   "LEO-USDT", "LET-USDT", "LHINU-USDT", "LINK-USDT", "LING-USDT", "LITH-USDT", "LON-USDT", "LOOKS-USDT", "LPT-USDT", 
                     //   "LQTY-USDT", "LRC-USDT", "LSK-USDT", "LTC-USDT", "LUNC-USDT", "LUNA-USDT", "MAGIC-USDT", "MANA-USDT", "MASK-USDT", 
                     //   "MDT-USDT", "MEME-USDT", "MENGO-USDT", "METIS-USDT", "MILO-USDT", "MINA-USDT", "MKR-USDT", "MLN-USDT", "MOVR-USDT",
                     //   "MOVEZ-USDT", "MRST-USDT", "MXC-USDT", "MYRIA-USDT", "NEAR-USDT", "NEO-USDT", "NFT-USDT", "NMR-USDT", "NULS-USDT",
                     //   "NYM-USDT", "OAS-USDT", "OM-USDT", "OMG-USDT", "OMI-USDT", "OMN-USDT", "ONE-USDT", "ONT-USDT", "OP-USDT", "ORBS-USDT",
                     //   "ORB-USDT", "OXT-USDT", "PCI-USDT", "PEOPLE-USDT", "PEPE-USDT", "PERP-USDT", "PHA-USDT", "PIT-USDT", "POLS-USDT", 
                     //   "POLYDOGE-USDT", "POR-USDT", "PRQ-USDT", "PSTAKE-USDT", "PYTH-USDT", "QTUM-USDT", "RACA-USDT", "RADAR-USDT", 
                     //   "RAY-USDT", "RDNT-USDT", "REN-USDT", "REP-USDT", "REVV-USDT", "RIO-USDT", "RNDR-USDT", "RON-USDT", "RPL-USDT", 
                     //   "RSR-USDT", "RSS3-USDT", "RVN-USDT", "SAMO-USDT", "SAND-USDT", "SC-USDT", "SD-USDT", "SHIB-USDT", "SIS-USDT", 
                     //   "SKEB-USDT", "SKL-USDT", "SLP-USDT", "SNT-USDT", "SNX-USDT", "SPELL-USDT", "SPURS-USDT", "SSV-USDT", "SSWP-USDT",
                     //   "STARL-USDT", "STC-USDT", "STETH-USDT", "STORJ-USDT", "STX-USDT", "SUI-USDT", "SUN-USDT", "SUSHI-USDT", "SWEAT-USDT",
                     //   "SWFTC-USDT", "T-USDT", "TAKI-USDT", "TAMA-USDT", "THETA-USDT", "THG-USDT", "TIA-USDT", "TON-USDT", "TRA-USDT", "TRB-USDT",
                     //   "TRX-USDT", "TUP-USDT", "TURBO-USDT", "UMA-USDT", "UNI-USDT", "USDC-USDT", "USTC-USDT", "UTK-USDT", "VELO-USDT", 
                     //   "VELODROME-USDT", "VELA-USDT", "VRA-USDT", "VSYS-USDT", "WAVES-USDT", "WAXP-USDT", "WBTC-USDT", "WGRT-USDT", "WIFI-USDT", 
                     //   "WIN-USDT", "WLD-USDT", "WNCG-USDT", "WOO-USDT", "WSB-USDT", "WSM-USDT", "WXT-USDT", "XAUT-USDT", "XCH-USDT", "XEC-USDT",
                     //   "XEM-USDT", "XETA-USDT", "XLM-USDT", "XMR-USDT", "XNO-USDT", "XPR-USDT", "XTZ-USDT", "YFI-USDT", "YFII-USDT", "YGG-USDT",
                     //   "ZBC-USDT", "ZEC-USDT", "ZEN-USDT", "ZIL-USDT", "ZKS-USDT","ZRX-USDT", "USDT-USDC"]

// const  BYBIT_SPOT_LIST = ['ZRXUSDT', 'ZILUSDT', 'ZENUSDT', 'YFIUSDT', 'XTZUSDT', 'XLMUSDT', 'XEMUSDT', 'WOOUSDT', 'WAXPUSDT', 'WAVESUSDT', 
//    /* REAL */           'VRAUSDT', 'USTCUSDT', 'UNIUSDT', 'UMAUSDT', 'TWTUSDT', 'TUSDT', 'TRXUSDT', 'TONUSDT', 'TOMIUSDT', 'TOKENUSDT', 'TIAUSDT', 
//                         'THETAUSDT', 'SWEATUSDT', 'SUSHIUSDT', 'SUNUSDT', 'SUIUSDT', 'STXUSDT', 'STGUSDT', 'SSVUSDT', 'SNXUSDT', 'SLPUSDT','SEIUSDT',
//                         'SCUSDT', 'SCRTUSDT', 'SANDUSDT', 'RVNUSDT', 'RUNEUSDT', 'RSS3USDT', 'RPLUSDT', 'ROSEUSDT', 'RNDRUSDT', 'RENUSDT', 'RDNTUSDT', 
//                         'QTUMUSDT', 'QNTUSDT', 'PERPUSDT', 'PEOPLEUSDT', 'PENDLEUSDT', 'PAXGUSDT', 'ORDIUSDT', 'OPUSDT', 'ONEUSDT', 'OMGUSDT', 
//                         'NEARUSDT', 'MOVRUSDT', 'MKRUSDT', 'MINAUSDT', 'MEMEUSDT', 'MATICUSDT', 'MASKUSDT', 'MANAUSDT', 'MAGICUSDT', 'LTCUSDT', 
//                         'LRCUSDT', 'LOOKSUSDT', 'LEVERUSDT', 'LDOUSDT', 'KSMUSDT', 'KLAYUSDT', 'KDAUSDT', 'KAVAUSDT', 'KASUSDT', 'JTOUSDT', 'JSTUSDT', 
//                         'JASMYUSDT', 'INJUSDT', 'IMXUSDT', 'IDUSDT', 'ICXUSDT', 'ICPUSDT', 'HOTUSDT', 'HOOKUSDT', 'HNTUSDT', 'HFTUSDT', 'HBARUSDT',
//                         'GRTUSDT', 'GPTUSDT', 'GODSUSDT', 'GMXUSDT', 'GMTUSDT', 'GLMRUSDT', 'GALAUSDT', 'FXSUSDT', 'FTTUSDT', 'FTMUSDT','FLRUSDT', 
//                         'FLOWUSDT', 'FITFIUSDT', 'FILUSDT', 'FETUSDT', 'ETHWUSDT', 'ETCUSDT', 'EOSUSDT', 'ENSUSDT', 'ENJUSDT', 'EGLDUSDT', 'DYDXUSDT', 
//                         'DOTUSDT', 'DGBUSDT', 'CYBERUSDT', 'CTCUSDT', 'CRVUSDT', 'COREUSDT', 'COMPUSDT', 'CHZUSDT', 'CELUSDT', 'CELOUSDT', 'CAKEUSDT',
//                         'C98USDT', 'BUSDUSDT', 'BOBAUSDT', 'BNTUSDT', 'BNBUSDT', 'BLURUSDT', 'BICOUSDT', 'BELUSDT', 'BEAMUSDT', 'BCHUSDT', 'BATUSDT', 
//                         'AXSUSDT', 'AXLUSDT', 'AVAXUSDT', 'ARUSDT', 'ARKMUSDT', 'ARBUSDT', 'APTUSDT', 'APEUSDT', 'ANKRUSDT', 'ALGOUSDT', 'AGLDUSDT', 
//                         'AGIXUSDT', 'AGIUSDT', 'ADAUSDT', 'ACHUSDT', 'AAVEUSDT', '1INCHUSDT', 'WLDUSDT', 'DOGEUSDT', 'LINKUSDT', 'XRPUSDT', 'MNTUSDT',
//                         'USDCUSDT', 'SOLUSDT', 'ETHUSDT', 'BTCUSDT',]

// const BYBIT_SPOT_LIST = ['BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'USDCUSDT', 'MNTUSDT', 'XRPUSDT', 'LINKUSDT', 'DOGEUSDT', 'WLDUSDT', 
//                      'NEONUSDT', '1INCHUSDT', '1SOLUSDT', '3PUSDT', '5IREUSDT', 'AAVEUSDT', 'ACAUSDT', 'ACHUSDT', 'ACMUSDT', 'ACSUSDT', 'ADA2LUSDT',
//                      'ADA2SUSDT', 'ADAUSDT', 'AFCUSDT', 'AGIUSDT', 'AGIXUSDT', 'AGLAUSDT', 'AGLDUSDT', 'ALGOUSDT', 'ANKRUSDT', 'APE2LUSDT', 'APE2SUSDT',
//                      'APEUSDT', 'APEXUSDT', 'APTUSDT', 'ARBUSDT', 'ARKMUSDT', 'ARUSDT', 'ATOM2LUSDT', 'ATOM2SUSDT', 'ATOMUSDT', 'AVAUSDT', 'AVAX2LUSDT',
//                      'AVAX2SUSDT', 'AVAXUSDT', 'AXLUSDT', 'AXSUSDT', 'AZYUSDT', 'BABYDOGEUSDT', 'BARUSDT', 'BATUSDT', 'BCHUSDT', 'BEAMUSDT', 'BELUSDT',
//                      'BICOUSDT', 'BLURUSDT', 'BNBUSDT', 'BNTUSDT', 'BOBAUSDT', 'BOBUSDT', 'BTC3LUSDT', 'BTC3SUSDT', 'BTGUSDT', 'BTTUSDT', 'BUSDUSDT', 
//                      'C98USDT', 'CAKEUSDT', 'CANDYUSDT', 'CAPOUSDT', 'CAPSUSDT', 'CATUSDT', 'CBXUSDT', 'CELOUSDT', 'CELUSDT', 'CGPTUSDT', 'CHRPUSDT', 
//                      'CHZUSDT', 'CITYUSDT', 'CMPUSDT', 'COMPUSDT', 'COREUSDT', 'COTUSDT', 'COUSDT', 'CRDSUSDT', 'CRVUSDT', 'CTCUSDT', 'CTTUSDT', 
//                      'CULTUSDT', 'CUSDUSDT', 'CWARUSDT', 'CYBERUSDT', 'DAIUSDT', 'DCRUSDT', 'DEFYUSDT', 'DEVTUSDT', 'DFIUSDT', 'DGBUSDT', 'DICEUSDT', 
//                      'DLCUSDT', 'DOGE2LUSDT', 'DOGE2SUSDT', 'DOMEUSDT', 'DOT3LUSDT', 'DOT3SUSDT', 'DOTUSDT', 'DPXUSDT', 'DSRUNUSDT', 'DYDXUSDT', 
//                      'DZOOUSDT', 'ECOXUSDT', 'EGLDUSDT', 'EGOUSDT', 'ELDAUSDT', 'ELTUSDT', 'ENJUSDT', 'ENSUSDT', 'EOS2LUSDT', 'EOS2SUSDT', 'EOSUSDT',
//                      'ERTHAUSDT', 'ETC2LUSDT', 'ETC2SUSDT', 'ETCUSDT', 'ETH3LUSDT', 'ETH3SUSDT', 'ETHWUSDT', 'EVERUSDT', 'FAMEUSDT', 'FBUSDT', 
//                      'FETUSDT', 'FIDAUSDT', 'FILUSDT', 'FITFIUSDT', 'FLIPUSDT', 'FLOKIUSDT', 'FLOWUSDT', 'FLRUSDT', 'FMBUSDT', 'FONUSDT', 'FORTUSDT',
//                      'FTM2LUSDT', 'FTM2SUSDT', 'FTMUSDT', 'FTTUSDT', 'FXSUSDT', 'GALAUSDT', 'GALFTUSDT', 'GALUSDT', 'GCAKEUSDT', 'GENEUSDT', 
//                      'GGMUSDT', 'GLMRUSDT', 'GMT2LUSDT', 'GMT2SUSDT', 'GMTUSDT', 'GMUSDT', 'GMXUSDT', 'GNSUSDT', 'GODSUSDT', 'GPTUSDT', 'GRTUSDT', 
//                      'GSTSUSDT', 'GSTUSDT', 'GSWIFTUSDT', 'HBARUSDT', 'HEROUSDT', 'HFTUSDT', 'HNTUSDT', 'HOOKUSDT', 'HOTUSDT', 'HVHUSDT', 'ICPUSDT', 
//                      'ICXUSDT', 'IDUSDT', 'IMXUSDT', 'INJUSDT', 'INSPUSDT', 'INTERUSDT', 'IZIUSDT', 'JASMYUSDT', 'JSTUSDT', 'JTOUSDT', 'JUVUSDT', 
//                      'KARATEUSDT', 'KASTAUSDT', 'KASUSDT', 'KAVAUSDT', 'KCALUSDT', 'KCSUSDT', 'KDAUSDT', 'KLAYUSDT', 'KMONUSDT', 'KOKUSDT', 
//                      'KONUSDT', 'KRLUSDT', 'KSMUSDT', 'KUNCIUSDT', 'LADYSUSDT', 'LDOUSDT', 'LEVERUSDT', 'LFWUSDT', 'LGXUSDT', 'LINGUSDT', 
//                      'LINK2LUSDT', 'LINK2SUSDT', 'LISUSDT', 'LMWRUSDT', 'LOOKSUSDT', 'LRCUSDT', 'LTC2LUSDT', 'LTC2SUSDT', 'LTCUSDT', 'LUNAUSDT',
//                      'LUNCUSDT', 'MAGICUSDT', 'MANAUSDT', 'MASKUSDT', 'MATIC2LUSDT', 'MATIC2SUSDT', 'MATICUSDT', 'MBSUSDT', 'MBXUSDT', 'MCRTUSDT',
//                      'MCTUSDT', 'MDAOUSDT', 'MEEUSDT', 'MELOSUSDT', 'MEMEUSDT', 'METHUSDT', 'MIBRUSDT', 'MINAUSDT', 'MIXUSDT', 'MKRUSDT', 'MLKUSDT',
//                      'MMCUSDT', 'MNZUSDT', 'MOVEZUSDT', 'MOVRUSDT', 'MPLXUSDT', 'MTKUSDT', 'MVLUSDT', 'MVUSDT', 'MXUSDT', 'NEARUSDT', 'NESSUSDT', 
//                      'NEXOUSDT', 'NEXTUSDT', 'NFTUSDT', 'NYMUSDT', 'OASUSDT', 'OBXUSDT', 'OKGUSDT', 'OMGUSDT', 'OMNUSDT', 'ONEUSDT', 'OPUSDT',
//                      'ORDIUSDT', 'ORTUSDT', 'PAXGUSDT', 'PENDLEUSDT', 'PEOPLEUSDT', 'PEPE2USDT', 'PEPEUSDT', 'PERPUSDT', 'PIPUSDT', 'PLANETUSDT', 
//                      'PLAYUSDT', 'PLTUSDT', 'PLYUSDT', 'POKTUSDT', 'POLUSDT', 'PPTUSDT', 'PRIMALUSDT', 'PRIMEUSDT', 'PSGUSDT', 'PSPUSDT', 
//                      'PSTAKEUSDT', 'PTUUSDT', 'PUMLXUSDT', 'PYUSDUSDT', 'QMALLUSDT', 'QNTUSDT', 'QTUMUSDT', 'RACAUSDT', 'RAINUSDT', 'RDNTUSDT', 
//                      'REALUSDT', 'RENUSDT', 'RLTMUSDT', 'RNDRUSDT', 'RONDUSDT', 'ROOTUSDT', 'ROSEUSDT', 'RPKUSDT', 'RPLUSDT', 'RSS3USDT', 'RUNEUSDT',
//                      'RVNUSDT', 'SAILUSDT', 'SAITAMAUSDT', 'SALDUSDT', 'SAND2LUSDT', 'SAND2SUSDT', 'SANDUSDT', 'SCRTUSDT', 'SCUSDT', 'SDUSDT', 
//                      'SEILORUSDT', 'SEIUSDT', 'SEORUSDT', 'SFUNDUSDT', 'SHIBUSDT', 'SHILLUSDT', 'SHRAPUSDT', 'SIDUSUSDT', 'SISUSDT', 'SLGUSDT', 
//                      'SLPUSDT', 'SNXUSDT', 'SOLOUSDT', 'SONUSDT', 'SOSUSDT', 'SPARTAUSDT', 'SPELLUSDT', 'SRMUSDT', 'SSVUSDT', 'STATUSDT', 
//                      'STETHUSDT', 'STGUSDT', 'STRMUSDT', 'STXUSDT', 'SUIAUSDT', 'SUIUSDT', 'SUNUSDT', 'SUSHIUSDT', 'SWEATUSDT', 'SYNRUSDT', 
//                      'TAMAUSDT', 'TAPUSDT', 'TAVAUSDT', 'TELUSDT', 'TENETUSDT', 'THETAUSDT', 'THNUSDT', 'TIAUSDT', 'TIMEUSDT', 'TOKENUSDT', 
//                      'TOMIUSDT', 'TONUSDT', 'TRIBEUSDT', 'TRVLUSDT', 'TRXUSDT', 'TURBOSUSDT', 'TUSDT', 'TUSDUSDT', 'TVKUSDT', 'TWTUSDT', 'UMAUSDT', 
//                      'UNIUSDT', 'USDDUSDT', 'USTCUSDT', 'VANRYUSDT', 'VEGAUSDT', 'VELAUSDT', 'VELOUSDT', 'VEXTUSDT', 'VINUUSDT', 'VPADUSDT', 
//                      'VRAUSDT', 'VRTXUSDT', 'VVUSDT', 'WAVESUSDT', 'WAXPUSDT', 'WBTCUSDT', 'WEMIXUSDT', 'WLKNUSDT', 'WOOUSDT', 'WWYUSDT', 'XAVAUSDT',
//                      'XCADUSDT', 'XDCUSDT', 'XECUSDT', 'XEMUSDT', 'XETAUSDT', 'XLMUSDT', 'XRP3LUSDT', 'XRP3SUSDT', 'XTZUSDT', 'XWGUSDT', 'XYMUSDT', 
//                      'YFIUSDT', 'ZAMUSDT', 'ZENUSDT', 'ZIGUSDT', 'ZILUSDT', 'ZRXUSDT', 'ZTXUSDT']




// const GATEIO_SPOT_LIST = ['gt_usdt', 'btc_usdt', 'eth_usdt', 'rats_usdt']
                     
const GATEIO_SPOT_LIST = ['gt_usdt', 'btc_usdt', 'eth_usdt', 'rats_usdt', 'sats_usdt', 'bonk_usdt', 'sols_usdt', 'ordi_usdt', 'avax_usdt', 'sol_usdt',
                    'arb_usdt', 'ftt_usdt', 'ada_usdt', 'inj_usdt', 'squad_usdt', 'doge_usdt', 'xrp_usdt', 'babygrok_usdt', 'fun_usdt', 'kas_usdt', 
                    'link_usdt', 'mubi_usdt', 'rndr_usdt', 'agix_usdt', 'pepe_usdt', 'dot_usdt', 'oax_usdt', 'stx_usdt', 'lqty_usdt', 'tia_usdt', 
                    'jto_usdt', 'icp_usdt', 'luna_usdt', 'astr_usdt', 'shib_usdt', 'flr_usdt', 'cfx_usdt', 'igu_usdt', 'pyth_usdt', 'zbu_usdt',
                    'ever_usdt', 'ftm_usdt', 'blur_usdt', 'hbar_usdt', 'ftn_usdt', 'ustc_usdt', 'pepe2_usdt', 'bigtime_usdt', 'astra_usdt', 
                    'fdusd_usdt', 'sui_usdt', 'atom_usdt', 'flow_usdt', 'btt_usdt', 'ladys_usdt', 'ape_usdt', 'alex_usdt', 'ntrn_usdt', 'dogi_usdt',
                    'grok_usdt', 'ousd_usdt', 'dydx_usdt', 'jasmy_usdt', 'vra_usdt', 'hnt_usdt', 'csix_usdt', 'op_usdt', 'ltc_usdt', 'imx_usdt', 
                    'bnb_usdt', 'fil_usdt', 'wld_usdt', 'fet_usdt', 'link5l_usdt', 'tomi_usdt', 'link5s_usdt', 'id_usdt', 'ctc_usdt', 'sei_usdt',
                    'gns_usdt', 'wemix_usdt', 'ocean_usdt', 'algo_usdt', 'voxel_usdt', 'xmr_usdt', 'snx_usdt', 'floki_usdt', 'rune_usdt', 
                    'matic_usdt', 'vgx_usdt', 'trx_usdt', 'sct_usdt', 'meme_usdt', 'xrd_usdt', 'near_usdt', 'aurora_usdt', 'sun_usdt', 'gala_usdt',
                    'rdnt_usdt', 'etc_usdt', 'eos_usdt', 'xcn_usdt', 'csas_usdt', 'beamx_usdt', 'cspr_usdt', 'auction_usdt', 'nft_usdt', 'gft_usdt',
                    'eth5s_usdt', 'waxl_usdt', 'btc5s_usdt', 'myria_usdt', 'apt_usdt', 'ethw_usdt', 'uni_usdt', 'win_usdt', 'iost_usdt', 'dot5s_usdt', 
                    'btc5l_usdt', 'flux_usdt', 'cheel_usdt', 'sushi_usdt', 'bch_usdt', 'lunc_usdt', 'fitfi_usdt', 'wagmigames_usdt', 'sidus_usdt',
                    'dot5l_usdt', 'nom_usdt', 'tao_usdt', 'usdd_usdt', 'woo_usdt', 'naka_usdt', 'pyr_usdt', 'cgpt_usdt', 'eth5l_usdt', 'ace_usdt', 
                    'crv_usdt', 'turbo_usdt', 'trac_usdt', 'cyber_usdt', 'rif_usdt', 'doge5s_usdt', 'xen_usdt', 'nals_usdt', 'dodo_usdt', 'egld_usdt', 
                    'syn_usdt', 'grt_usdt', 'neon_usdt', 'raca_usdt', 'xcad_usdt', 'kda_usdt', 'flip_usdt', 'doge5l_usdt', 'majo_usdt', 'arkm_usdt', 
                    'rfd_usdt', 'xrp5l_usdt', 'psl_usdt', 'storj_usdt', 'abt_usdt', 'usdc_usdt', 'jst_usdt', 'unfi_usdt', 'rose_usdt', 'coreum_usdt', 
                    'lai_usdt', 'trb_usdt', 'ast_usdt', 'carbon_usdt', 'hifi_usdt', 'doggo_usdt', 'vmpx_usdt', 'wsm_usdt', 'velo_usdt', 'mask_usdt',
                    'fida_usdt', 'srm_usdt', 'mina_usdt', 'aidoge_usdt', 'babydoge_usdt', 'token_usdt', 'super_usdt', 'xlm_usdt', 'gala5l_usdt', 
                    'hook_usdt', 'ygg_usdt', 'uni5l_usdt', 'jam_usdt', 'metis_usdt', 'sand_usdt', 'mana_usdt', 'polyx_usdt', 'goal_usdt', 'aioz_usdt',
                    'orai_usdt', 'looks_usdt', 'opul_usdt', 'pokt_usdt', 'pizabrc_usdt', 'ml_usdt', 'akt_usdt', 'atlas_usdt', 'catheon_usdt',
                    'benqi_usdt', 'ar_usdt', 'bdx_usdt', 'ceek_usdt', 'aitech_usdt', 'alph_usdt', 'clore_usdt', 'mpl_usdt', 'bsv_usdt', 'azero_usdt',
                    'cake_usdt', 'xrp5s_usdt', 'cro_usdt', 'biso_usdt', 'stik_usdt', 'ht_usdt', 'chz_usdt', 'edu_usdt', 'erg_usdt', 'shib5s_usdt',
                    'hai_usdt', 'pica_usdt', 'ton_usdt', 'gmt_usdt', 'tara_usdt', 'phb_usdt', 'vc_usdt', 'brise_usdt', 'bake_usdt', 'caga_usdt', 
                    'gala5s_usdt', 'xeta_usdt', 'planet_usdt', 'xdc_usdt', 'aave_usdt', 'loom_usdt', 'pace_usdt', 'sfund_usdt', 'bbc_usdt', 
                    'zbc_usdt', 'hft_usdt', 'music_usdt', 'cook_usdt', 'vet_usdt', 'qtum_usdt', 'lite_usdt', 'root_usdt', 'aog_usdt', 'shib5l_usdt',
                    'fnsa_usdt', 'like_usdt', 'insp_usdt', 'dao_usdt', 'cti_usdt', 'combo_usdt', 'ltc5s_usdt', 'iota_usdt', 'f3_usdt', 'lsd7_usdt',
                    'sdao_usdt', 'boba_usdt', 'spa_usdt', 'vai_usdt', 'qrdo_usdt', 'bnt_usdt', 'tlos_usdt', 'skl_usdt', 'slim_usdt', 'magic_usdt', 
                    'prx_usdt', 'paal_usdt', 'okt_usdt', 'kct_usdt', 'mav_usdt', 'prom_usdt', 'agi_usdt', 'zig_usdt', 'route_usdt', 'store_usdt', 
                    'pendle_usdt', 'prime_usdt', 'wojak_usdt', 'dione_usdt', 'ggg_usdt', 'people_usdt', 'war_usdt', 'png_usdt', 'glmr_usdt', 
                    'ovr_usdt', 'prq_usdt', 'ltc5l_usdt', 'ssv_usdt', 'samo_usdt', 'rare_usdt', 'eml_usdt', 'gfi_usdt', 'nano_usdt', 'seam_usdt',
                    'rpl_usdt', 'oas_usdt', 'cfg_usdt', '1inch_usdt', 'stg_usdt', 'bone_usdt', 'reap_usdt', 'mong_usdt', 'xch_usdt', 'lina_usdt',
                    'chapz_usdt', 'navi_usdt', 'waves_usdt', 'labs_usdt', 'sclp_usdt', 'acs_usdt', 'kicks_usdt', 'bbank_usdt', 'pols_usdt', 
                    'rpk_usdt', 'cho_usdt', 'arks_usdt', 'slp_usdt', 'xpr_usdt', 'ray_usdt', 'pbr_usdt', 'enj_usdt', 'kava_usdt', 'qanx_usdt',
                    'pepebrc_usdt', 'uni5s_usdt', 'nada_usdt', 'ox_usdt', 'nos_usdt', 'man_usdt', 'flm_usdt', 'gmmt_usdt', 'xtag_usdt', 'gmee_usdt', 
                    'ufo_usdt', 'frm_usdt', 'xava_usdt', 'slrs_usdt', 'eos5l_usdt', 'cru_usdt', 'sin_usdt', 'iotx_usdt', 'ali_usdt', 'ooki_usdt', 
                    'arch_usdt', 'raft_usdt', 'xcv_usdt', 'iron_usdt', 'cirus_usdt', 'yesp_usdt', 'next_usdt', 'vtho_usdt', 'pmg_usdt', 'fear_usdt', 
                    'swash_usdt', 'isp_usdt', 'axs_usdt', 'dag_usdt', 'starl_usdt', 'dck_usdt', 'dmtr_usdt', 'blok_usdt', 'lpt_usdt', 'mblk_usdt', 
                    'ckb_usdt', 'vanry_usdt', 'mnde_usdt', 'isk_usdt', 'cqt_usdt', 'ens_usdt', 'neer_usdt', 'noot_usdt', 'gf_usdt', 'sxp_usdt', 
                    'trade_usdt', 'moni_usdt', 'mxc_usdt', 'gst_usdt', 'core_usdt', 'amc_usdt', 'one_usdt', 'movr_usdt', 'eqx_usdt', 'zec_usdt', 
                    'kap_usdt', 'wlkn_usdt', 'crpt_usdt', 'theta_usdt', 'cvtx_usdt', 'pogai_usdt', 'vxt_usdt', 'akita_usdt', 'optimus_usdt', 
                    'zil_usdt', 'orn_usdt', 'xdb_usdt', 'ejs_usdt', 'chr_usdt', 'niza_usdt', 'mbox_usdt', 'zen_usdt', 'cetus_usdt', 'drac_usdt', 
                    'og_usdt', 'fly_usdt', 'bankbrc_usdt', 'bch5l_usdt', 'trias_usdt', 'ong_usdt', 'nbot_usdt', 'c98_usdt', 'senate_usdt', 
                    'kishu_usdt', 'orca_usdt', 'fcon_usdt', 'derc_usdt', 'realm_usdt', 'bond_usdt', 'ctsi_usdt', 'num_usdt', 'crown_usdt', 
                    'bts_usdt', 'stbu_usdt', 'solo_usdt', 'type_usdt', 'cpool_usdt', 'bch5s_usdt', 'sov_usdt', 'bsvbrc_usdt', 'ztx_usdt', 
                    'cere_usdt', 'ach_usdt', 'shibai_usdt', 'yfii_usdt', 'psub_usdt', 'dash_usdt', 'meld_usdt', 'vts_usdt', 'arbi_usdt', 'ron_usdt', 
                    'sylo_usdt', 'mplx_usdt', 'qnt_usdt', 'kub_usdt', 'dc_usdt', 'gmm_usdt', 'jpg_usdt', 'fxs_usdt', 'wbt_usdt', 'bico_usdt', 
                    'wgrt_usdt', 'dora_usdt', 'ksm_usdt', 'gas_usdt', 'omg_usdt', 'beam_usdt', 'dusk_usdt', 'elon_usdt', 'cmp_usdt', 'nsdx_usdt', 
                    'dark_usdt', 'smurfcat_usdt', 'fyn_usdt', 'neo_usdt', 'sbr_usdt', 'pbx_usdt', 'mmpro_usdt', 'hot_usdt', 'uos_usdt', 'mdao_usdt', 
                    'domi_usdt', 'ldo_usdt', 'suip_usdt', 'kin_usdt', 'osmo_usdt', 'cudos_usdt', 'unibot_usdt', 'celo_usdt', 'ewt_usdt', 'key_usdt', 
                    'joe_usdt', 'biop_usdt', 'zlk_usdt', 'poolx_usdt', 'front_usdt', 'pond_usdt', 'aca_usdt', 'sdex_usdt', 'vrtx_usdt', 'high_usdt', 
                    'memebrc_usdt', 'deso_usdt', 'mob_usdt', 'cweb_usdt', 'vlx_usdt', 'lava_usdt', 'vinu_usdt', 'vext_usdt', 'taki_usdt', 'akro_usdt', 
                    'mlt_usdt', 'dfi_usdt', 'els_usdt', 'izi_usdt', 'abbc_usdt', 'stnd_usdt', 'dyp_usdt', 'alpha_usdt', 'idea_usdt', 'aleph_usdt', 
                    'ilv_usdt', 'mtrg_usdt', 'badger_usdt', 'perp_usdt', 'berry_usdt', 'axs5s_usdt', 'nerd_usdt', 'blankv2_usdt', 'tru_usdt', 
                    'api3_usdt', 'gari_usdt', 'pumlx_usdt', 'lbr_usdt', 'agld_usdt', 'buy_usdt', 'fnz_usdt', 'axs5l_usdt', 'flokiceo_usdt', 'rad_usdt', 
                    'saito_usdt', 'fra_usdt', 'zks_usdt', 'ren_usdt', 'wwy_usdt', 'coti_usdt', 'rlc_usdt', 'sgb_usdt', 'ankr_usdt', 'hdv_usdt', 
                    'myth_usdt', 'dust_usdt', 'ais_usdt', 'lss_usdt', 'wild_usdt', 'xpll_usdt', 'alice_usdt', 'dorkl_usdt', 'qi_usdt', 'tama_usdt',
                    'bzz_usdt', 'ngl_usdt', 'troy_usdt', 'sis_usdt', 'bnc_usdt', 'souls_usdt', 'arpa_usdt', 'game_usdt', 'hard_usdt', 'oct_usdt', 
                    'gal_usdt', 'intr_usdt', 'paw_usdt', 'pha_usdt', 'alu_usdt', 'chng_usdt', 'xyo_usdt', 'ferc_usdt', 'mdx_usdt', 'polc_usdt', 
                    'hello_usdt', 'undead_usdt', 'pzp_usdt', 'perl_usdt', 'npt_usdt', 'rbn_usdt', 'velodrome_usdt', 'polis_usdt', 'liq_usdt',
                    'shft_usdt', 'loka_usdt', 'aisc_usdt', 'rite_usdt', 'math_usdt', 'pip_usdt', 'revoland_usdt', 'hapi_usdt', 'cell_usdt', 'hod_usdt', 
                    'bel_usdt', 'lrc_usdt', 'eos5s_usdt', 'obi_usdt', 'klay_usdt', 'ads_usdt', 'bld_usdt', 'epik_usdt', 'strax_usdt', 'band_usdt', 
                    'rbc_usdt', 'oxy_usdt', 'vr_usdt', 'smart_usdt', 'somm_usdt', 'dek_usdt', 'clv_usdt', 'rfox_usdt', 'nftb_usdt', 'wsi_usdt', 
                    'sweat_usdt', 'king_usdt', 'pit_usdt', 'pnt_usdt', 'wifi_usdt', 'wmt_usdt', 'dcrn_usdt', 'stos_usdt', 'psi_usdt', 'lmwr_usdt', 
                    'mnw_usdt', 'grail_usdt', 'btg_usdt', 'amp_usdt', 'tsuka_usdt', 'dent_usdt', 'nct_usdt', 'lmr_usdt', 'dome_usdt', 'metfi_usdt', 
                    'tip_usdt', 'clh_usdt', 'knft_usdt', 'reef_usdt', 'bear_usdt', 'volt_usdt', 'wsb_usdt', 'jgn_usdt', 'sys_usdt', 'bsw_usdt', 
                    'play_usdt', 'iag_usdt', 'glq_usdt', 'celr_usdt', 'shill_usdt', 'quick_usdt', 'block_usdt', 'teer_usdt', 'bscpad_usdt', 'elf_usdt', 
                    'brn_usdt', 'wrx_usdt', 'pando_usdt', 'sc_usdt', 'xvs_usdt', 'omi_usdt', 'okb_usdt', 'kar_usdt', 'solr_usdt', 'timechrono_usdt', 
                    'waxp_usdt', 'boson_usdt', 'htr_usdt', 'psp_usdt', 'mkr_usdt', 'spo_usdt', 'arv_usdt', 'cwar_usdt', 'rss3_usdt', 'xtz_usdt', 
                    'lym_usdt', 'adx_usdt', 'anml_usdt', 'anc_usdt', 'swap_usdt', 'free_usdt', 'mtv_usdt', 'hech_usdt', 'ern_usdt', 'aibb_usdt', 
                    'bat_usdt', 'gomining_usdt', 'amb_usdt', 'fevr_usdt', 'dbc_usdt', 'ooe_usdt', 'ham_usdt', 'cult_usdt', 'xym_usdt', 'doga_usdt', 
                    'bgt_usdt', 'comp_usdt', 'wncg_usdt', 'derp_usdt', 'tenet_usdt', 'earn_usdt', 'utk_usdt', 'cat_usdt', 'cbk_usdt', 'xwg_usdt', 
                    'pros_usdt', 'xels_usdt', 'gmx_usdt', 'nftl_usdt', 'ogv_usdt', 'cos_usdt', 'dexe_usdt', 'rvn_usdt', 'mir_usdt', 'nmr_usdt', 
                    'dhx_usdt', 'falcons_usdt', 'lamb_usdt', 'snt_usdt', 'tt_usdt', 'land_usdt', 'soil_usdt', 'turbos_usdt', 'karate_usdt', 
                    'shib2_usdt', 'orbs_usdt', 'atolo_usdt', 'dino_usdt', 'df_usdt', 'thg_usdt', 'rly_usdt', 'gafi_usdt', 'wit_usdt', 'mlk_usdt', 
                    'feg_usdt', 'ecox_usdt', 'ats_usdt', 'iris_usdt', 'dg_usdt', 'hxa_usdt', 'suku_usdt', 'dio_usdt', 'bdp_usdt', 'blz_usdt', 
                    'rjv_usdt', 'uma_usdt', 'ioi_usdt', 'rari_usdt', 'ela_usdt', 'vdr_usdt', 'fdc_usdt', 'ride_usdt', 'bscs_usdt', 'ont_usdt', 
                    'zee_usdt', 'woop_usdt', 'maro_usdt', 'swftc_usdt', 'alcx_usdt', 'sdn_usdt', 'powr_usdt', 'sos_usdt', 'mean_usdt', 'btrst_usdt', 
                    'fbx_usdt', 'meto_usdt', 'adp_usdt', 'pts_usdt', 'hero_usdt', 'nkn_usdt', 'zrx_usdt', 'mbs_usdt', 'canto_usdt', 'dego_usdt', 
                    'walv_usdt', 'vemp_usdt', 'ing_usdt', 'soul_usdt', 'matter_usdt', 'frr_usdt', 'xend_usdt', 'was_usdt', 'pstake_usdt', 'rena_usdt', 
                    'tusd_usdt', 'mdt_usdt', 'pooh_usdt', 'scrt_usdt', 'nblu_usdt', 'lit_usdt', 'gm_usdt', 'nux_usdt', 'axl_usdt', 'home_usdt', 
                    'acm_usdt', 'tlm_usdt', 'alpaca_usdt', 'trcl_usdt', 'bnx_usdt', 'cheq_usdt', 'gaypepe_usdt', 'ogn_usdt', 'peri_usdt', 'zlw_usdt',
                     'ftrb_usdt', 'loop_usdt', 'crp_usdt', 'gno_usdt', 'mnz_usdt', 'ttt_usdt', 'klo_usdt', 'kma_usdt', 'dnxc_usdt', 'xec_usdt', 
                     'radar_usdt', 'zcx_usdt', 'rei_usdt', 'ctk_usdt', 'ufi_usdt', 'htm_usdt', 'qkc_usdt', 'kube_usdt', 'tfuel_usdt', 'dar_usdt', 
                     'chess_usdt', 'rmrk_usdt', 'dcr_usdt', 'xet_usdt', 'maps_usdt', 'vic_usdt', 'twt_usdt', 'milo_usdt', 'unq_usdt', 'xem_usdt', 
                     'step_usdt', 'wam_usdt', 'olt_usdt', 'lime_usdt', 'icx_usdt', 'ubxs_usdt', 'yfi_usdt', 'kono_usdt', 'forth_usdt', 'wrt_usdt', 
                     'kp3r_usdt', 'dpr_usdt', 'pdex_usdt', 'sudo_usdt', 'hopr_usdt', 'plspad_usdt', 'marsh_usdt', 'roco_usdt', 'egame_usdt', 
                     'lyx_usdt', 'tsugt_usdt', 'opn_usdt', 'porto_usdt', 'epx_usdt', 'fis_usdt', 'd2t_usdt', '10set_usdt', 'qtc_usdt', 'lgx_usdt', 
                     'om_usdt', 'xprt_usdt', 'sti_usdt', 'bp_usdt', 'nrfb_usdt', 'boo_usdt', 'muse_usdt', 'rbls_usdt', 'sero_usdt', 'vega_usdt',
                      'leash_usdt', 'hive_usdt', 'sny_usdt', 'req_usdt', 'lith_usdt', 'ark_usdt', 'sfp_usdt', 'gofx_usdt', 'umee_usdt', 'cgg_usdt', 
                      'wing_usdt', 'lm_usdt', 'cvp_usdt', 'hera_usdt', 'gth_usdt', 'soph_usdt', 'hegic_usdt', 'revv_usdt', 'cys_usdt', 'spellfire_usdt',
                       'cate_usdt', 'o3_usdt', 'reign_usdt', 'cream_usdt', 'mls_usdt', 'nxd_usdt', 'movez_usdt', 'gzone_usdt', 'yfdai_usdt', 'mnt_usdt',
                        'dia_usdt', 'dhb_usdt', 'well_usdt', 'xcur_usdt', 'bank_usdt', 'knc_usdt', 'plcu_usdt', 'bcd_usdt', 'adapad_usdt', 'rsr_usdt',
                         'lovely_usdt', 'lat_usdt', 'kbox_usdt', 'revu_usdt', 'ring_usdt', 'wbird_usdt', 'locg_usdt', 'spurs_usdt', 'ant_usdt', 
                         'supe_usdt', 'mimir_usdt', 'tko_usdt', 'drep_usdt', 'bal_usdt', 'pine_usdt', 'btm_usdt', 'lto_usdt', 'whale_usdt', 
                         'gitcoin_usdt', 'stmx_usdt', 'heart_usdt', 'doge2_usdt', 'xmon_usdt', 'multi_usdt', 'gear_usdt', 'pym_usdt', 'sfm_usdt',
                          'ethf_usdt', 'pmon_usdt', 'mv_usdt', 'kyve_usdt', 'wkc_usdt', 'nvir_usdt', 'aqdc_usdt', 'oxt_usdt', 'bondly_usdt',
                           'pkf_usdt', 'ae_usdt', 'xdefi_usdt', 'nym_usdt', 'santos_usdt', 'hns_usdt', 'sandwich_usdt', 'clips_usdt', 'tips_usdt', 
                           'sway_usdt', 'redtoken_usdt', 'ass_usdt', 'mts_usdt', 'xpla_usdt', 'mpi_usdt', '1earth_usdt', 'dfa_usdt', 'itsb_usdt', 
                           'nodl_usdt', 'slk_usdt', 'wbtc_usdt', 'omn_usdt', 'gbpt_usdt', 'hmt_usdt', 'cws_usdt', 'sail_usdt', 'qash_usdt', 
                           'steem_usdt', 'nvg_usdt', 'dsla_usdt', 'asm_usdt', 'delfi_usdt', 'hoge_usdt', 'cvc_usdt', 'mbx_usdt', 'pol_usdt', 
                           'polydoge_usdt', 'aergo_usdt', 'seilor_usdt', 'wag_usdt', 'dmc_usdt', 'zelix_usdt', 'gxe_usdt', 'wear_usdt', 'aart_usdt', 
                           'bepro_usdt', 'tidal_usdt', 'atm_usdt', 'suia_usdt', 'mobi_usdt', 'gq_usdt', 'apx_usdt', 'hmtt_usdt', 'ranker_usdt', 
                           'kasta_usdt', 'spirit_usdt', 'ava_usdt', 'grv_usdt', 'wzm_usdt', 'infra_usdt', 'slc_usdt', 'yooshi_usdt', 'dvi_usdt', 
                           'defiland_usdt', 'btcst_usdt', 'impt_usdt', 'dfyn_usdt', 'saitama_usdt', 'watt_usdt', 'sponge_usdt', 'chain_usdt',
                           'kton_usdt', 'lion_usdt', 'mco2_usdt', 'champ_usdt', 'grnd_usdt', 'lavita_usdt', 'wallet_usdt', 'hid_usdt', 'shi_usdt',
                           'alpine_usdt', 'spell_usdt', 'grin_usdt', 'ppt_usdt', 'ole_usdt', 'firo_usdt', 'cal_usdt', 'caps_usdt', 'audio_usdt',
                           'xvg_usdt', 'xed_usdt', 'wnz_usdt', 'oddz_usdt', 'wzrd_usdt', 'push_usdt', 'zzz_usdt', 'bamboo_usdt', 'mtl_usdt',
                           'psg_usdt', 'wxt_usdt', 'toke_usdt', 'orc_usdt', 'wsg_usdt', 'hydra_usdt', 'xor_usdt', 'fio_usdt', 'ted_usdt',
                           'logt_usdt', 'moov_usdt', 'cvx_usdt', 'slnd_usdt', 'pig_usdt', 'paf_usdt', 'zix_usdt', 'data_usdt', 'artem_usdt', 
                           'mdf_usdt', 'piza_usdt', 'ctt_usdt', 'lunr_usdt', 'perc_usdt', 'sashimi_usdt', 'uno_usdt', 'oin_usdt', 'gcoin_usdt',
                           'cgv_usdt', 'bac_usdt', 'bsv5l_usdt', 'k21_usdt', 'rep_usdt', 'orb_usdt', 'nest_usdt', 'mini_usdt', 'ata_usdt', 
                           'acn_usdt', 'fsn_usdt', 'krl_usdt', 'lpool_usdt', 'ares_usdt', 'noia_usdt', 'squid_usdt', 'kok_usdt', 'por_usdt',
                           'taboo_usdt', 'kilt_usdt', 'nord_usdt', 'yin_usdt', 'etha_usdt', 'lever_usdt', 'hord_usdt', 'dose_usdt', 'gold_usdt',
                           'dock_usdt', 'b3x_usdt', 'srk_usdt', 'brkl_usdt', 'uft_usdt', 'rdn_usdt', 'nftd_usdt', 'hc_usdt', 'nfty_usdt', 
                           'xnl_usdt', 'skill_usdt', 'polk_usdt', 'city_usdt', 'kft_usdt', 'baby_usdt', 'ratio_usdt', 'sps_usdt', 'mist_usdt', 
                           'cart_usdt', 'thn_usdt', 'fuse_usdt', 'dep_usdt', 't_usdt', 'aie_usdt', 'hotcross_usdt', 'ampl_usdt', 'dpet_usdt', 
                           'pundix_usdt', 'blt_usdt', 'dana_usdt', 'naos_usdt', 'wfai_usdt', 'catgirl_usdt', 'shx_usdt', 'conv_usdt',
                           'pop_usdt', 'ghst_usdt', '1art_usdt', 'hades_usdt', 'asto_usdt', 'stox_usdt', 'msu_usdt', 'ortb_usdt',
                            'airtnt_usdt', 'mln_usdt', 'ref_usdt', 'asr_usdt', 'doggy_usdt', 'vrx_usdt', 'mix_usdt', 'urus_usdt', 
                            'dop_usdt', 'amkt_usdt', 'teddy_usdt', 'life_usdt', 'ppad_usdt', 'mgg_usdt', 'vlxpad_usdt', 'mngo_usdt',
                            'edg_usdt', 'acx_usdt', 'nuls_usdt', 'snm_usdt', 'tools_usdt', 'auto_usdt', 'tap_usdt', 'star_usdt', 
                            'xaut_usdt', 'haha_usdt', 'bmex_usdt', 'tpt_usdt', 'luffy_usdt', 'spay_usdt', 'eul_usdt', 'kai_usdt',
                            'dks_usdt', 'ibfk_usdt', 'wozx_usdt', 'stpt_usdt', 'sunny_usdt', 'for_usdt', 'trace_usdt', 'idex_usdt',
                            'knight_usdt', 'pixel_usdt', 'maha_usdt', 'boa_usdt', 'strp_usdt', 'bird_usdt', 'adel_usdt', 'nwc_usdt',
                            'atem_usdt', 'shr_usdt', 'frin_usdt', 'stc_usdt', 'eth2_usdt', 'mcrt_usdt', 'polypad_usdt', 'fdt_usdt', 
                            'xpnet_usdt', 'sao_usdt', 'primal_usdt', 'rekt_usdt', 'gaia_usdt', 'hyve_usdt', 'kine_usdt', 'pla_usdt',
                            'cel_usdt', 'pcx_usdt', 'dis_usdt', 'tari_usdt', 'xpress_usdt', 'dxct_usdt', 'lazio_usdt', 'form_usdt', 
                            'dognft_usdt', 'ald_usdt', 'portx_usdt', 'trvl_usdt', 'savg_usdt', 'raze_usdt', 'zam_usdt', 'nftx_usdt',
                            'nii_usdt', 'ask_usdt', 'zodi_usdt', 'bdt_usdt', 'ggm_usdt', 'ag_usdt', 'vidyx_usdt', 'astro_usdt', 
                            'arrr_usdt', 'kpad_usdt', 'layer_usdt', 'beefi_usdt', 'dzoo_usdt', 'four_usdt', 'mepad_usdt', 'ioen_usdt',
                            'nsbt_usdt', 'strm_usdt', 'pet_usdt', 'he_usdt', 'fire_usdt', 'glm_usdt', 'avt_usdt', 'mtr_usdt',
                            'lkr_usdt', 'rfuel_usdt', 'knot_usdt', 'moon_usdt', 'bft1_usdt', 'aura_usdt', 'atk_usdt', 'bxh_usdt',
                            'juld_usdt', 'vee_usdt', 'razor_usdt', 'dos_usdt', 'afc_usdt', 'pvu_usdt', 'quack_usdt', 'ita_usdt', 
                            'juv_usdt', 'wagyu_usdt', 'nexo_usdt', 'senso_usdt', 'ome_usdt', 'vader_usdt', 'tra_usdt', 'loot_usdt',
                            'farm_usdt', 'nyzo_usdt', 'rin_usdt', 'boring_usdt', 'sbtc_usdt', 'fin_usdt', 'woof_usdt', 'tulip_usdt',
                            'mcash_usdt', 'env_usdt', 'klv_usdt', 'eq_usdt', 'sonar_usdt', 'larix_usdt', 'kint_usdt', 'bs_usdt', 
                            'arg_usdt', 'swrv_usdt', 'baseptl_usdt', 'lemn_usdt', 'hsf_usdt', 'kuma_usdt', 'bcmc_usdt', 'kalm_usdt',
                            'zat_usdt', 'wnxm_usdt', 'metal_usdt', 'pot_usdt', 'tonc_usdt', 'mmm_usdt', 'ddd_usdt', 'mrch_usdt', 'psy_usdt', 
                            'craft_usdt', 'baked_usdt', 'bifif_usdt', 'west_usdt', 'port_usdt', 'smt_usdt', 'snft_usdt', 'hct_usdt', 'prt_usdt',
                            'xy_usdt', 'nrv_usdt', 'go_usdt', '4token_usdt', 'btl_usdt', 'cre8_usdt', 'vera_usdt', 'jfi_usdt', 'eternal_usdt', 
                            'salt_usdt', 'lemd_usdt', 'diver_usdt', 'god_usdt', 'opium_usdt', 'yfx_usdt', 'taur_usdt', 'f2c_usdt', 'kgc_usdt', 
                            'occ_usdt', 'rndx_usdt', 'bin_usdt', 'pi_usdt', 'sop_usdt', 'empire_usdt', 'zeum_usdt', 'mswap_usdt', 'corn_usdt', 
                            'naft_usdt', 'isky_usdt', 'susd_usdt', 'gdao_usdt', 'opa_usdt', 'tribe_usdt', 'bbf_usdt', 'loa_usdt', 'gmat_usdt', 
                            'scnsol_usdt', 'golc_usdt', 'rage_usdt', 'kcal_usdt', 'onit_usdt', 'hpb_usdt', 'mm_usdt', 'vtg_usdt', 'cher_usdt', 
                            'fpft_usdt', 'skyrim_usdt', 'wex_usdt', 'pnl_usdt', 'bcx_usdt', 'vso_usdt', 'inter_usdt', 'gse_usdt', 'theos_usdt', 
                            'mph_usdt', 'open_usdt', 'mengo_usdt', 'rfr_usdt', 'ess_usdt', 'bmi_usdt', 'lfw_usdt', 'bacon_usdt', 'mooo_usdt', 
                            'bitci_usdt', 'skrt_usdt', 'bnty_usdt', 'lbk_usdt', 'mbl_usdt', 'vatreni_usdt', 'shopx_usdt', 'kws_usdt', 'ehash_usdt', 
                            'room_usdt', 'kiba_usdt', 'deri_usdt', 'flx_usdt', 'prmx_usdt', 'nbs_usdt', 'clo_usdt', 'rvc_usdt', 'kmon_usdt',
                            'suter_usdt', 'emon_usdt', 'trg_usdt', 'brick_usdt', 'gem_usdt', 'qtcon_usdt', 'pride_usdt', 'spfc_usdt', 'kex_usdt', 
                            'stz_usdt', 'black_usdt', 'mga_usdt', 'knj_usdt', 'ez_usdt', 'ocn_usdt', 'skt_usdt', 'upi_usdt', 'mesa_usdt', 
                            'frax_usdt', 'bles_usdt', 'inv_usdt', 'ttk_usdt', 'srp_usdt', 'pay_usdt', 'pcnt_usdt', 'angle_usdt', 'lus_usdt', 
                            'egg_usdt', 'ovo_usdt', 'qsp_usdt', 'wsienna_usdt', 'forex_usdt', 'enno_usdt', 'lon_usdt', 'bmon_usdt', 'shopnext_usdt', 
                            'xil_usdt', 'pst_usdt', 'fame_usdt', 'dx_usdt', 'liquidus_usdt', 'altb_usdt', 'single_usdt', 'cir_usdt', 'imayc_usdt', 
                            'octo_usdt', 'bcug_usdt', 'fnf_usdt', 'pias_usdt', 'cstr_usdt', 'oshi_usdt', 'onx_usdt', 'talk_usdt', 'pyme_usdt', 
                            'babi_usdt', 'myra_usdt', 'flurry_usdt', 'gan_usdt', 'sd_usdt', 'busy_usdt', 'klima_usdt', 'dog_usdt', 'yam_usdt', 
                            'kimchi_usdt', 'icons_usdt', 'crf_usdt', 'ionx_usdt', 'duck_usdt', 'alpa_usdt', 'tbe_usdt', 'am_usdt', 'atd_usdt', 
                            'itgr_usdt', 'lien_usdt', 'vp_usdt', 'the_usdt', 'mot_usdt', 'evry_usdt', 'azy_usdt', 'tdrop_usdt', 'metax_usdt', 
                            'lemo_usdt', 'vsp_usdt', 'yct_usdt', 'xnft_usdt', 'uncx_usdt', 'pera_usdt', 'oland_usdt', 'dfl_usdt', 'cs_usdt', 
                            'elec_usdt', 'fiwa_usdt', 'aly_usdt', 'ctrc_usdt', 'udo_usdt', 'arsw_usdt', 'dai_usdt', 'dms_usdt', 'rem_usdt', 
                            'spex_usdt', 'thales_usdt', 'fort_usdt', 'vent_usdt', 'dlc_usdt', 'kbd_usdt', 'vvs_usdt', 'kon_usdt', 'gens_usdt', 
                            'ssx_usdt', 'ams_usdt', 'psb_usdt', 'mofi_usdt', 'nim_usdt', 'kt_usdt', 'swop_usdt', 'tnc_usdt', 'crt_usdt', 
                            'rai_usdt', 'bto_usdt', 'apn_usdt', 'dfnd_usdt', 'ort_usdt', 'bas_usdt', 'tita_usdt', 'aln_usdt', 'srt_usdt', 
                            'carat_usdt', 'klap_usdt', 'real_usdt', 'posi_usdt', 'safereum_usdt', 'ags_usdt', 'scy_usdt', 'kingshib_usdt', 
                            'dpy_usdt', 'trr_usdt', 'axis_usdt', 'dmlg_usdt', 'lowb_usdt', 'bora_usdt', 'noa_usdt', 'fxf_usdt', 'sntr_usdt', 
                            'leo_usdt', 'aicode_usdt', 'med_usdt', 'lgcy_usdt', 't23_usdt', 'ztg_usdt', 'oro_usdt', 'deus_usdt', 'sup_usdt', 
                            'mda_usdt', 'tsl_usdt', 'lsd_usdt', 'qbt_usdt', 'lblock_usdt', 'fst_usdt', 'prare_usdt', 'nax_usdt', 'item_usdt', 
                            'fodl_usdt', 'sauber_usdt', 'red_usdt', 'yld_usdt', 'fan_usdt', 'cre_usdt', 'lsk_usdt', 'kzen_usdt', 'dka_usdt', 
                            'cover_usdt', 'metaldr_usdt', 'poli_usdt', 'slnv2_usdt', 'ddos_usdt', 'wicc_usdt', 'mat_usdt', 'lbl_usdt', 'crts_usdt', 
                            'unn_usdt', 'des_usdt', 'kfc_usdt', 'cofix_usdt', 'tross_usdt', 'prism_usdt', 'celt_usdt', 'ruff_usdt', 'bry_usdt', 
                            'wista_usdt', 'fx_usdt', 'asw_usdt', 'credit_usdt', 'alaya_usdt', 'fiu_usdt', 'metan_usdt', 'fuel_usdt', 'cup_usdt',
                            'mql_usdt', 'agb_usdt', 'pool_usdt', 'aped_usdt', 'dv_usdt', 'ink_usdt', 'aiepk_usdt', 'sake_usdt', 'brwl_usdt', 
                            'safemars_usdt', 'elu_usdt', 'tct_usdt', 'brt_usdt', 'moma_usdt', 'dvp_usdt', 'bifi_usdt', 'sfil_usdt', 'gdt_usdt', 
                            'kst_usdt', 'byn_usdt', 'zoon_usdt', 'ghny_usdt', 'esg_usdt', 'mape_usdt', 'ad_usdt', 'far_usdt', 'snk_usdt', 
                            'nift_usdt', 'gasdao_usdt', 'tifi_usdt', 'zsc_usdt', 'bcdn_usdt', 'kaby_usdt', 'para_usdt', 'bxc_usdt', 'rice_usdt', 
                            'bft_usdt', 'niifi_usdt', 'vela_usdt', 'debt_usdt', 'alphr_usdt', 'fncy_usdt', 'beyond_usdt', 'gard_usdt', 'tcp_usdt', 
                            'usdg_usdt', 'gxa_usdt', 'ful_usdt', 'gum_usdt', 'fox_usdt', 'gnx_usdt', 'orion_usdt', 'mtd_usdt', 'zone_usdt', 'atoz_usdt',
                            'joy_usdt', 'mojo_usdt', 'snow_usdt', 'mhunt_usdt', 'nmt_usdt', 'props_usdt', 'dal_usdt', 'sphri_usdt', 'totm_usdt', 
                            'onc_usdt', 'bvt_usdt', 'tshp_usdt', 'mart_usdt', 'cfi_usdt', 'mooney_usdt', 'lba_usdt', 'care_usdt', 'sfty_usdt', 
                            'rim_usdt', 'place_usdt', 'slice_usdt', 'ala_usdt', 'snft1_usdt', 'pwar_usdt', 'txt_usdt', 'eden_usdt', 'filda_usdt', 
                            'lrn_usdt', 'argon_usdt', 'swth_usdt', 'iht_usdt', 'pickle_usdt', 'smty_usdt', 'digg_usdt', 'wiken_usdt', 'eurt_usdt', 
                            'furucombo_usdt', 'cusd_usdt', 'coval_usdt', 'unistake_usdt', 'toms_usdt', 'egs_usdt', 'tai_usdt', 'tapt_usdt', 'mtn_usdt', 
                            'moo_usdt', 'hsc_usdt', 'hget_usdt', 'shoe_usdt', 'ost_usdt', 'bcn_usdt', 'ops_usdt', 'motg_usdt', 'hit_usdt', 'gov_usdt', 
                            'eva_usdt', 'mis_usdt', 'sn_usdt', 'unt_usdt', 'asd_usdt', 'oly_usdt', 'white_usdt', 'gof_usdt', 'cofi_usdt', 'hibs_usdt', 
                            'aag_usdt', 'xmc_usdt', 'fine_usdt', 'olv_usdt', 'atp_usdt', 'ceur_usdt', 'apys_usdt', 'sfi_usdt', 'dhv_usdt', 'value_usdt', 
                            'sfg_usdt', 'lavaswap_usdt', 'orbr_usdt', 'kif_usdt', 'skm_usdt', 'kat_usdt', 'box_usdt', 'spume_usdt', 'eosdac_usdt', 
                            'mds_usdt', 'blin_usdt', 'coral_usdt', 'nas_usdt', 'rcn_usdt', 'galo_usdt', 'gel_usdt', 'phtr_usdt', 'cummies_usdt', 
                            'dafi_usdt', 'agla_usdt', 'hao_usdt', 'xrune_usdt', 'vrt_usdt', 'bly_usdt', 'ame_usdt', 'aqt_usdt', 'vidy_usdt', 
                            'frog_usdt', 'gtc_usdt', 'bkc_usdt', 'loon_usdt', 'cname_usdt', 'skeb_usdt', 'goldminer_usdt', 'crvusd_usdt', 
                            'swo_usdt', 'lev_usdt', 'dili_usdt', 'source_usdt', 'slg_usdt', 'rft_usdt', 'arcx_usdt', 'senc_usdt', 'sku_usdt', 
                            'pbtc35a_usdt', 'orao_usdt', 'nap_usdt', 'mgkl_usdt', 'share_usdt', 'rdf_usdt', 'mine_usdt', 'ibayc_usdt', 'fer_usdt', 
                            'vmt_usdt', 'drgn_usdt', 'vno_usdt', 'cnns_usdt', 'iazuki_usdt', 'wom_usdt', 'mcrn_usdt', 'met_usdt', 'pnk_usdt', 
                            'dfy_usdt', 'moda_usdt', 'fti_usdt', 'muratiai_usdt', 'mint_usdt', 'burp_usdt', 'lunch_usdt', 'czz_usdt', 'eeg_usdt', 
                            'phm_usdt', 'snet_usdt', '3km_usdt', 'idv_usdt', 'nebl_usdt', 'mta_usdt', '88mph_usdt', 'zpt_usdt', 'roobee_usdt', 
                            'strong_usdt', 'meli_usdt', 'umb_usdt', 'bags_usdt', 'gs_usdt', 'match_usdt', 'mtg_usdt', 'geta_usdt', 'qwan_usdt', 
                            'slm_usdt', 'indi_usdt', 'nbt_usdt', 'srg_usdt', 'hln_usdt', 'mith_usdt', 'insur_usdt', 'ulu_usdt', 'rating_usdt', 
                            'idoodles_usdt', 'shping_usdt', 'ktn_usdt', 'agility_usdt', 'itrump_usdt', 'yield_usdt', 'nbp_usdt', 'ram_usdt', 
                            'ateam_usdt', 'grbe_usdt', 'zcn_usdt', 'sccp_usdt', 'gmpd_usdt', 'galfan_usdt', 'popk_usdt', 'ihc_usdt', 'nsure_usdt', 
                            'zmt_usdt', 'btf_usdt', 'cvaultcore_usdt', 'air_usdt', 'pearl_usdt', 'sugarb_usdt', 'bsv5s_usdt', 'msol_usdt', 
                            'govi_usdt', 'akv_usdt', 'ipunks_usdt', 'ons_usdt', 'stsol_usdt', 'p00ls_usdt', 'goz_usdt', 'cty_usdt', 'steth_usdt', 
                            'bfc_usdt', 'wndr_usdt', 'pyusd_usdt', 'baju_usdt', 'ctg_usdt', 'usdp_usdt', 'fei_usdt', 'pog_usdt', 'spi_usdt', 
                            'wings_usdt', 'grap_usdt', 'dsd_usdt', 'stake_usdt', 'xmark_usdt', 'mcg_usdt', 'gob_usdt', 'betu_usdt', 'tbtc_usdt', 
                            'revo_usdt', 'duck2_usdt', 'zkt_usdt', 'tvk_usdt', 'mars_usdt', 'esd_usdt', 'usdn_usdt', 'ccar_usdt', 'rltm_usdt', 
                            'zinu_usdt', 'efi_usdt', 'cdt_usdt', 'vpr_usdt', 'time_usdt', 'hibiki_usdt', 'reelt_usdt', 'tox_usdt', 'ice_usdt', 
                            'ip3_usdt', 'squidgrow_usdt', 'stepg_usdt', 'bao_usdt', 'lyxe_usdt', 'ipad_usdt', 'vrjam_usdt', 'ddim_usdt', 
                            'iqt_usdt', 'rgt_usdt', 'ping_usdt', 'cryptofi_usdt', 'aimx_usdt', 'sersh_usdt', 'mfootball_usdt', 'visr_usdt', 
                            'l3p_usdt', 'renbtc_usdt', 'tokau_usdt', 'ramp_usdt', 'sswp_usdt']
                                      

export const BINANCE_FUTURES = BINANCE_FUTURES_LIST
export const BINANCE_SPOT    = BINANCE_SPOT_LIST
export const OKX_SPOT        = OKX_SPOT_LIST
export const BYBIT_SPOT      = BYBIT_SPOT_LIST
export const GATEIO_SPOT     = GATEIO_SPOT_LIST